#!/usr/bin/env pwsh
# The single per-build version step on Windows (decisions 15/25): compute Day + Time + git hash ONCE and write
# eng/obj/version.g.props that every project imports. See eng/version.sh for the model.
#
# Usage: eng/version.ps1 [-Channel dev]   channel "dev" => -pre-release; anything else => release.
[CmdletBinding()]
param([string]$Channel = $env:AGENTGUARD_CHANNEL)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

$epoch = [DateTimeOffset]::FromUnixTimeSeconds(1577836800).UtcDateTime   # 2020-01-01
$now = [DateTime]::UtcNow
$day = [int][Math]::Floor(($now - $epoch).TotalDays)
$time = [int][Math]::Floor($now.TimeOfDay.TotalSeconds / 2)
$combined = $day * 43200 + $time
# Robust even when git is absent / this is not a repo (PS 7.4 turns a non-zero native exit into a throw).
$hash = 'local'
try { $h = git rev-parse --short=7 HEAD 2>$null; if ($LASTEXITCODE -eq 0 -and $h) { $hash = $h } } catch { }

New-Item -ItemType Directory -Force -Path "$ScriptDir/obj" | Out-Null
@"
<Project>
  <!-- Generated by eng/version.ps1; git-ignored; the single shared version for this build (decision 25). -->
  <PropertyGroup>
    <AgentGuardDay>$day</AgentGuardDay>
    <AgentGuardTime>$time</AgentGuardTime>
    <AgentGuardCombined>$combined</AgentGuardCombined>
    <AgentGuardHash>$hash</AgentGuardHash>
    <AgentGuardChannel>$Channel</AgentGuardChannel>
  </PropertyGroup>
</Project>
"@ | Set-Content -NoNewline "$ScriptDir/obj/version.g.props"
Write-Host "version.g.props: Day=$day Time=$time Combined=$combined Hash=$hash Channel=$Channel"
