#!/usr/bin/env bash
# The single per-build version step (decisions 15/25): compute Day + Time + git hash ONCE and write
# eng/obj/version.g.props, which every project imports — so a build that straddles a 2-second tick still
# stamps one version. Run this before `dotnet build` for an authoritative version; a bare build without it
# uses a non-authoritative local fallback (Day/Time 0, hash "local").
#
# Usage: eng/version.sh [channel]   channel "dev" => -pre-release; anything else => release (no prerelease id).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHANNEL="${1:-${AGENTGUARD_CHANNEL:-}}"

EPOCH=1577836800                      # 2020-01-01T00:00:00Z, in Unix seconds
NOW=$(date -u +%s)
DAY=$(( (NOW - EPOCH) / 86400 ))       # whole days since 2020-01-01 (UTC)
TIME=$(( (NOW % 86400) / 2 ))          # floor(seconds-since-midnight / 2), range 0..43199
COMBINED=$(( DAY * 43200 + TIME ))     # the SemVer third field
HASH=$(git rev-parse --short=7 HEAD 2>/dev/null || echo local)

mkdir -p "$SCRIPT_DIR/obj"
cat > "$SCRIPT_DIR/obj/version.g.props" <<EOF
<Project>
  <!-- Generated by eng/version.sh; git-ignored; the single shared version for this build (decision 25). -->
  <PropertyGroup>
    <AgentGuardDay>$DAY</AgentGuardDay>
    <AgentGuardTime>$TIME</AgentGuardTime>
    <AgentGuardCombined>$COMBINED</AgentGuardCombined>
    <AgentGuardHash>$HASH</AgentGuardHash>
    <AgentGuardChannel>$CHANNEL</AgentGuardChannel>
  </PropertyGroup>
</Project>
EOF
echo "version.g.props: Day=$DAY Time=$TIME Combined=$COMBINED Hash=$HASH Channel=${CHANNEL:-<release>}"
